version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  app:
    build: .
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  vite:
    image: node:18-alpine
    container_name: laravel-vite
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
    driver: local